spring:
  mail:
    # Configuración de correo electrónico para enviar notificaciones
    username: paseomodernosupp@gmail.com # Nombre de usuario de la cuenta de correo electrónico
    port: '587' # Puerto de correo electrónico
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
          timeout: '5000'
    host: smtp.gmail.com # Servidor de correo electrónico
    protocol: smtp # Protocolo de correo electrónico
    password: uadzsmfgiwhwkior # Contraseña de la cuenta de correo electrónico
    host_address: http://localhost:8080 # Dirección del servidor de la aplicación
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # Controlador de la base de datos MySQL
    password: asdf # Contraseña de la base de datos
    username: root # Nombre de usuario de la base de datos
    url: jdbc:mysql://localhost:3306/paseomoderno?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # URL de conexión a la base de datos MySQL
  servlet:
    multipart:
      max-file-size: 10MB # Tamaño máximo permitido de un archivo subido
      max-request-size: 10MB # Tamaño máximo permitido de una solicitud HTTP
  mvc:
    dispatch-options-request: 'true'
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
swagger:
  contact:
    email: daw09.2022@gmail.com # Dirección de correo electrónico del contacto de Swagger
    url: .. # URL del sitio web del contacto de Swagger
    name: Adi Danut Mihalachi # Nombre del contacto de Swagger
  host:
    path: /swagger-ui/ # Ruta para acceder a la interfaz de usuario de Swagger
    address: localhost:8080 # Dirección del servidor de la aplicación
  api:
    version: v1 # Versión de la API de Swagger
    name: Paseo Moderno Docs # Nombre de la documentación de Swagger